[theme]
primaryColor = "#66d024ff"  # Hex code for blue (change as needed)
backgroundColor = "#FFFFFF"  # White background
secondaryBackgroundColor = "#F0F2F6"  # Light gray for sidebars/secondary areas
textColor = "#262730"  # Dark text
font = "sans serif"  # Or "serif", "monospace"